pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = "us-east-1"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Validate'){
            steps{
                sh 'terraform validate'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan -out tfplan'
                stash name: 'tfplan', includes: 'tfplan'
            }
        }

        stage('Terraform Apply') {

            steps {
                unstash 'tfplan'
                sh 'terraform apply tfplan'
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { return params.DESTROY_INFRA == true }
            }
            steps {
                sh 'terraform destroy -auto-approve'
            }
        }

    }

    parameters {
            booleanParam(name: 'DESTROY_INFRA', defaultValue: false, description: 'set true to destroy infra')
        }
}